GLOBAL.setfenv(1, GLOBAL)

-- TUNING.GOBLINKILLER_HEALTH = 150
-- TUNING.GOBLINKILLER_HUNGER = 150
-- TUNING.GOBLINKILLER_SANITY = 200

TUNING.SHADOW_ABIGAIL_DAMAGE = {
    day = 10,
    dusk = 20,
    night = 30,
}
