STRINGS.SKILLTREE.SISTURN_LOCK_DESC = "学习三级受佑姐妹骨灰罐技能"

STRINGS.ACTIONS.SUMMON_SMALLGHOST = "通灵召唤"

STRINGS.ACTIONS.DEPLOY.RELOCATION = "改葬"
STRINGS.ACTIONS.DEPLOY.REINTERMENT = "移灵"

STRINGS.ACTIONS.UPGRADE.CONDOLENCE_BOUQUET = "哀悼献花"

STRINGS.ACTIONS.GRAVE_RELOCATION = {
    GENERIC = "改葬",
    ENCOFFIN = "收殓",
    REINTERMENT = "移灵",
}

STRINGS.CHARACTERS.WENDY.ACTIONFAIL.SUMMON_SMALLGHOST = {
    NOTHOME = "我感觉到他们不在家里",
    COOLDOWN = "不总是能与他们沟通上",
}

STRINGS.NAMES.POSSESSED_GHOSTFLOWER = "被附身的哀悼荣耀"
