STRINGS.SKILLTREE.SISTURN_LOCK_DESC = "学习三级受佑姐妹骨灰罐技能"

STRINGS.ACTIONS.SUMMON_SMALLGHOST = "通灵召唤"

STRINGS.CHARACTERS.WENDY.ACTIONFAIL.SUMMON_SMALLGHOST = {
    NOTHOME = "我感觉到他们不在家里",
    COOLDOWN = "不总是能与他们沟通上",
}
