STRINGS.SKILLTREE.SISTURN_LOCK_DESC = "学习三级受佑姐妹骨灰罐技能"

STRINGS.ACTIONS.SUMMON_SMALLGHOST = "通灵召唤"

STRINGS.ACTIONS.DEPLOY.RELOCATION = "改葬"
STRINGS.ACTIONS.DEPLOY.REINTERMENT = "移灵"

STRINGS.ACTIONS.UPGRADE.CONDOLENCE_BOUQUET = "哀悼献花"

STRINGS.ACTIONS.GRAVE_RELOCATION = {
    GENERIC = "改葬",
    ENCOFFIN = "收殓",
    REINTERMENT = "移灵",
}
STRINGS.CHARACTERS.WENDY.ACTIONFAIL.SUMMON_SMALLGHOST = {
    NOTHOME = "我感觉到他们不在家里",
    ONEGHOST = "我一次只能渡一个灵魂达到目的地",
    COOLDOWN = "不总是能与他们沟通上",
}

STRINGS.ACTIONS.PRESENT = "赠礼"
STRINGS.CHARACTERS.WENDY.ACTIONFAIL.PRESENT = {
    ENOUGH = "灵魂们不需要更多的慰藉了",
}

STRINGS.CHARACTERS.WENDY.USE_ELIXIR_CONTAINER_WITHNOT_SKILL = "不一定会永远得不到想要的东西，但有些人永远只会被唾弃"

STRINGS.NAMES.POSSESSED_GHOSTFLOWER = "被附身的哀悼荣耀"

STRINGS.NAMES.MOON_TREE_BLOSSOM_LANTERN = "月树花灯"
